source 'https://rubygems.org'
gemspec

gem 'flow_base',        path: '../base'
gem 'flow-queue',       path: '../queue'
gem 'cassandra',        github: 'brainopia/cassandra'
gem 'cassandra-mapper', github: 'brainopia/cassandra-mapper'
gem 'floq',             github: 'brainopia/floq'
gem 'floq-redis',       github: 'brainopia/floq'
